<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <PackageId>Chameleon.Net</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BouncyCastle.Cryptography" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="ZstdSharp.Port" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Chameleon.Net.Tests" />
    </ItemGroup>
</Project>
